package Pasta_pagamento;

import java.time.LocalDate;

public class view_pagamento extends javax.swing.JFrame {

    int idPedido = 1;
    double valorPedido = 200.50;

    /**
     * Creates new form view_pagamento
     */
    public view_pagamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        mtdPag_comboBox = new javax.swing.JComboBox<>();
        txtVlrPedido = new javax.swing.JTextField();
        lblDinheiro = new javax.swing.JLabel();
        lblTroco = new javax.swing.JLabel();
        txtVlrTotal = new javax.swing.JTextField();
        txtTroco = new javax.swing.JTextField();
        btnFinalizar = new javax.swing.JButton();
        lblValor = new javax.swing.JLabel();
        txtDinheiro = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnConsultarPgm = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PAGAMENTO");
        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));
        setPreferredSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Pedido"
            }
        ));
        jScrollPane1.setViewportView(tblPedidos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 56, 310, 350));

        mtdPag_comboBox.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        mtdPag_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Debito", "Credito", "Pix", "Dinheiro" }));
        mtdPag_comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtdPag_comboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(mtdPag_comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 140, -1));

        txtVlrPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVlrPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(txtVlrPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 140, -1));

        lblDinheiro.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblDinheiro.setText("DINHEIRO");
        getContentPane().add(lblDinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        lblTroco.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblTroco.setText("TROCO");
        getContentPane().add(lblTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        txtVlrTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVlrTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtVlrTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 109, -1));

        txtTroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrocoActionPerformed(evt);
            }
        });
        getContentPane().add(txtTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 140, -1));

        btnFinalizar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnFinalizar.setText("FINALIZAR");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, -1, -1));

        lblValor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblValor.setText("VALOR");
        getContentPane().add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, -1));
        getContentPane().add(txtDinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 140, -1));

        btnCalcular.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        btnConsultarPgm.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnConsultarPgm.setText("PAGAMENTOS");
        btnConsultarPgm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPgmActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultarPgm, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PAGAMENTO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 720, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mtdPag_comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtdPag_comboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mtdPag_comboBoxActionPerformed

    private void txtVlrPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVlrPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVlrPedidoActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed

        String mtdPagamento = "";
        LocalDate data = LocalDate.now();
        double vlrPedido = 0;
        int IDPedido = idPedido;

        mtdPagamento = (String) mtdPag_comboBox.getSelectedItem();
        vlrPedido = valorPedido;

        pagamento_DTO dto = new pagamento_DTO();
        dto.setData(data);
        dto.setFormaDePagamento(mtdPagamento);
        dto.setIdPedido(IDPedido);
        dto.setValorPedido(valorPedido);

        pagamentoDAO dao = new pagamentoDAO();
        dao.save(dto);

    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void txtVlrTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVlrTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVlrTotalActionPerformed

    private void txtTrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrocoActionPerformed

    private void btnConsultarPgmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPgmActionPerformed
        consultarPagamento telaConsultaPagamento = new consultarPagamento();
        telaConsultaPagamento.setLocationRelativeTo(null);
        telaConsultaPagamento.setVisible(true);
    }//GEN-LAST:event_btnConsultarPgmActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        double vlrPedido = 0, vlrDinheiro = 0, vlrTotal = 0, vlrTroco = 0;
        vlrPedido = Double.parseDouble(txtVlrPedido.getText());
        vlrDinheiro = Double.parseDouble(txtDinheiro.getText());
        vlrTroco = vlrDinheiro - vlrPedido;
        txtTroco.setText(String.valueOf(vlrTroco));
        vlrTotal = vlrPedido;
        txtVlrTotal.setText("150");
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_pagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnConsultarPgm;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDinheiro;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JLabel lblValor;
    private javax.swing.JComboBox<String> mtdPag_comboBox;
    private javax.swing.JTable tblPedidos;
    private javax.swing.JTextField txtDinheiro;
    private javax.swing.JTextField txtTroco;
    private javax.swing.JTextField txtVlrPedido;
    private javax.swing.JTextField txtVlrTotal;
    // End of variables declaration//GEN-END:variables
}
