/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pasta_pedidos;

import Pasta_Login.usuario_DTO;
import Pasta_cliente.cliente_DTO;
import Pasta_estoque.Estoque_DAO;
import Pasta_estoque.estoque_DTO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jeff & Carla
 */
public class CadastroPedidosView extends javax.swing.JFrame {
    
    
    double getPreco;
    
    estoque_DTO objDTO = new estoque_DTO();
    Estoque_DAO objDAO = new Estoque_DAO();

    /**
     * Creates new form CadastroPedidosView
     */
    public CadastroPedidosView() {
        initComponents();      
    }
    
    
    public void exportarDados_Cliente(cliente_DTO objDTO){
            txt_ID_Cliente.setText(Integer.toString(objDTO.getChave_Primaria()));
            txt_Nome_Cliente.setText(objDTO.getNome());
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPedidos = new javax.swing.JTable();
        txtDescricao = new javax.swing.JLabel();
        txtAreaDescricao = new java.awt.TextArea();
        txtObservacao = new javax.swing.JLabel();
        AreaObservacao = new java.awt.TextArea();
        Quantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        Valor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnSalvar = new java.awt.Button();
        btnPagamento = new java.awt.Button();
        btnAdicionar = new java.awt.Button();
        btnExcluir = new java.awt.Button();
        btnPesquisar = new java.awt.Button();
        btnLimpar = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_ID_Cliente = new javax.swing.JTextField();
        txt_Nome_Cliente = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pedidos");
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PEDIDOS");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1250, -1));

        tabelaPedidos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tabelaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Lanches", "Valor"
            }
        ));
        tabelaPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DescricaoAutomatica(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPedidos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 300, 560));

        txtDescricao.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtDescricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDescricao.setText("DESCRIÇÃO");
        getContentPane().add(txtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 480, -1));

        txtAreaDescricao.setEditable(false);
        txtAreaDescricao.setEnabled(false);
        txtAreaDescricao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txtAreaDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 480, 200));

        txtObservacao.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtObservacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtObservacao.setText("OBSERVAÇÃO");
        getContentPane().add(txtObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 480, 20));

        AreaObservacao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(AreaObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 490, 240));

        Quantidade.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Quantidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Quantidade.setText("QUANTIDADE");
        getContentPane().add(Quantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 60, 160, -1));

        txtQuantidade.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });
        getContentPane().add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 90, 100, 40));

        Valor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Valor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Valor.setText("VALOR TOTAL");
        getContentPane().add(Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 550, 140, 20));

        txtValor.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtValor.setText(" ");
        txtValor.setEnabled(false);
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 582, 110, 40));

        btnSalvar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnSalvar.setLabel("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 610, 80, 40));

        btnPagamento.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnPagamento.setLabel("PAGAMENTO");
        btnPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 630, 110, 40));

        btnAdicionar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnAdicionar.setLabel("ADICIONAR");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 140, 100, 40));

        btnExcluir.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnExcluir.setLabel("EXCLUIR");
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 610, 80, 40));

        btnPesquisar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnPesquisar.setLabel("PESQUISAR");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 90, 40));

        btnLimpar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnLimpar.setLabel("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 610, 90, 40));

        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txt_ID_Cliente.setEnabled(false);
        getContentPane().add(txt_ID_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 60, -1));

        txt_Nome_Cliente.setEnabled(false);
        getContentPane().add(txt_Nome_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 90, -1));

        jFormattedTextField1.setText("jFormattedTextField1");
        getContentPane().add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 590, 110, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO código da pesquisa para o banco esta aqui nesse botão de Pesquisar
        String filtro="";
        DefaultTableModel pedidos = (DefaultTableModel) tabelaPedidos.getModel();
        pedidos.setNumRows(0);
        ArrayList<estoque_DTO> listaDTO = objDAO.Consultaproduto(filtro);
        
        for (int num = 0; num < listaDTO.size(); num++) {
            pedidos.addRow(new Object[]{
            
                listaDTO.get(num).getId(),
                listaDTO.get(num).getNome(),
                listaDTO.get(num).getPreco(),
                
            });
        }
        
        
        
        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
       //precisa arrumar a conta pois não está funcionando os calculos.
        
        double
                quantidade, resultado = 0, tentarSoma= 0, somaTotal = 0;
       
       quantidade = Double.parseDouble(txtQuantidade.getText());
       
       resultado = (getPreco * quantidade) + tentarSoma;
      
       String teste = String.valueOf(somaTotal);
       
       somaTotal = somaTotal + tentarSoma;
       
       txtValor.setText(teste);
       tentarSoma = Double.parseDouble(txtValor.getText());
  
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        
    txtAreaDescricao.setText("");
    AreaObservacao.setText("");
    
    // Limpa o campo de quantidade
    txtQuantidade.setText("");
    
    // Limpa o campo de valor
    txtValor.setText("");

    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void DescricaoAutomatica(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescricaoAutomatica
        // TODO add your handling code here:
        Estoque_DAO objDAO = new Estoque_DAO();
        estoque_DTO objDTO = new estoque_DTO();
        
        String
                pegar_id_tabela, pegar_preco_tabela;
        
        int
                linha_clicada_tabela;
        
        linha_clicada_tabela = tabelaPedidos.getSelectedRow();
        pegar_id_tabela = (tabelaPedidos.getModel().getValueAt(linha_clicada_tabela, 0).toString());
        
        objDTO = objDAO.ConsultarID(Integer.parseInt(pegar_id_tabela));
        
        txtAreaDescricao.setText(objDTO.getDescricao());
        
        pegar_preco_tabela = (tabelaPedidos.getModel().getValueAt(linha_clicada_tabela, 2).toString());
        getPreco = Double.parseDouble(pegar_preco_tabela);       
    }//GEN-LAST:event_DescricaoAutomatica

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtValorActionPerformed

    private void btnPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPedidosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPedidosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPedidosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPedidosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPedidosView().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea AreaObservacao;
    private javax.swing.JLabel Quantidade;
    private javax.swing.JLabel Valor;
    private java.awt.Button btnAdicionar;
    private java.awt.Button btnExcluir;
    private java.awt.Button btnLimpar;
    private java.awt.Button btnPagamento;
    private java.awt.Button btnPesquisar;
    private java.awt.Button btnSalvar;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaPedidos;
    private java.awt.TextArea txtAreaDescricao;
    private javax.swing.JLabel txtDescricao;
    private javax.swing.JLabel txtObservacao;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txt_ID_Cliente;
    private javax.swing.JTextField txt_Nome_Cliente;
    // End of variables declaration//GEN-END:variables

}
