/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pasta_estoque;


/**
 *
 * @author omaci
 */
public class estoque_Cadastrar_VIEW extends javax.swing.JFrame {
        int ID_cliente;
    /**
     * Creates new form estoque_Cadastrar_VIEW
     */
    public estoque_Cadastrar_VIEW() {
        initComponents();
    }
    
    public void exportar_ID_Produto(estoque_DTO objDTO){
        lbl_ID.setText(Integer.toString(objDTO.getId()));
        txt_nome_produto.setText(objDTO.getNome());
        txt_descricao.setText(objDTO.getDescricao());
        txt_preco_produto.setText(String.valueOf(objDTO.getPreco()));
        
        ID_cliente = objDTO.getId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nome_produto = new javax.swing.JTextField();
        txt_preco_produto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_descricao = new javax.swing.JTextArea();
        btn_salvar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbl_ID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");
        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));
        setPreferredSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("CADASTRO DE PRODUTOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, 36));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setText("NOME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setText("PREÇO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setText("DESCRIÇÃO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));
        getContentPane().add(txt_nome_produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 190, 32));
        getContentPane().add(txt_preco_produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 190, 32));

        txt_descricao.setColumns(20);
        txt_descricao.setRows(5);
        jScrollPane1.setViewportView(txt_descricao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 330, 130));

        btn_salvar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn_salvar.setText("SALVAR");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, -1, -1));

        jLabel5.setText("ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));
        getContentPane().add(lbl_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 70, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        
        if (ID_cliente == 0) {
            Salvar_Dados();
        }
        else if(ID_cliente != 0){
            AlterarDados();
        }
        
      
    }//GEN-LAST:event_btn_salvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(estoque_Cadastrar_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(estoque_Cadastrar_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(estoque_Cadastrar_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(estoque_Cadastrar_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new estoque_Cadastrar_VIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JTextArea txt_descricao;
    private javax.swing.JTextField txt_nome_produto;
    private javax.swing.JTextField txt_preco_produto;
    // End of variables declaration//GEN-END:variables

    public void AlterarDados(){
        estoque_DTO objDTO = new estoque_DTO();
        int ID;
        String nome, descricao;
        double preco;
        Estoque_DAO objDAO = new Estoque_DAO();
        
        ID = Integer.parseInt(lbl_ID.getText());
        nome = txt_nome_produto.getText();
        descricao = txt_descricao.getText();
        preco = Double.parseDouble(txt_preco_produto.getText());
        
        objDTO.setId(ID);
        objDTO.setNome(nome);
        objDTO.setDescricao(descricao);
        objDTO.setPreco(preco);
        
        objDAO.alterar_Cardapio_Completo(objDTO);
    
    }
    
    public void Salvar_Dados(){
         String nome, descricao;
        double preco;
        
        nome = txt_nome_produto.getText();
        descricao = txt_descricao.getText();
        preco = Double.parseDouble(txt_preco_produto.getText());
        
        estoque_DTO objcadastro = new estoque_DTO();
        
        
        objcadastro.setNome(nome);
        objcadastro.setDescricao(descricao);
        objcadastro.setPreco(preco);
        
        Estoque_DAO EstDAO = new Estoque_DAO();
        EstDAO.cadastraProduto(objcadastro);
    
    }


}
