/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pasta_estoque;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author omaci
 */
public class Estoque_consulta_VIEW extends javax.swing.JFrame {
    estoque_DTO objDTOAlterar = new estoque_DTO();
    int ID_Excluir_Dados;
    /**
     * Creates new form Estoque_consulta_VIEW
     */
    public Estoque_consulta_VIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Descricao = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        txt_fltro = new javax.swing.JTextField();
        btn_Consulta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_alterar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_cadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cardápio");
        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));
        setPreferredSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("CONSULTAR CARDAPIO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        txt_Descricao.setColumns(20);
        txt_Descricao.setRows(5);
        jScrollPane1.setViewportView(txt_Descricao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 610, 133));

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "NOME", "PREÇO"
            }
        ));
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carregar_descricao_automatico(evt);
            }
        });
        jScrollPane2.setViewportView(Tabela);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 610, 118));

        txt_fltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fltroActionPerformed(evt);
            }
        });
        getContentPane().add(txt_fltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 209, -1));

        btn_Consulta.setText("Consulta");
        btn_Consulta.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                btn_ConsultaAncestorRemoved(evt);
            }
        });
        btn_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setText("PESQUISAR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, -1, -1));

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_fltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fltroActionPerformed

    private void btn_ConsultaAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btn_ConsultaAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ConsultaAncestorRemoved

    private void btn_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConsultaActionPerformed
        Consultar();
    }//GEN-LAST:event_btn_ConsultaActionPerformed

    private void Carregar_descricao_automatico(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carregar_descricao_automatico
        Estoque_DAO objDAO = new Estoque_DAO();
        estoque_DTO objDTO = new estoque_DTO();
        int Selecionar_linha_clicada;
        String Capturar_Id_da_Linha,Capturar_nome_da_Linha,Capturar_Preco_da_Linha;
        
        Selecionar_linha_clicada = Tabela.getSelectedRow();
        
        Capturar_Id_da_Linha = (Tabela.getModel().getValueAt(Selecionar_linha_clicada, 0).toString());
        Capturar_nome_da_Linha = (Tabela.getModel().getValueAt(Selecionar_linha_clicada, 1).toString());
        Capturar_Preco_da_Linha = (Tabela.getModel().getValueAt(Selecionar_linha_clicada, 2).toString());
              
        
        objDTO = objDAO.ConsultarID(Integer.parseInt(Capturar_Id_da_Linha));
        
        txt_Descricao.setText(objDTO.getDescricao());
        
        ID_Excluir_Dados=Integer.parseInt(Capturar_Id_da_Linha);
        
        objDTOAlterar.setId(Integer.parseInt(Capturar_Id_da_Linha));
        objDTOAlterar.setNome(Capturar_nome_da_Linha);
        objDTOAlterar.setPreco(Double.parseDouble(Capturar_Preco_da_Linha));    
        
    }//GEN-LAST:event_Carregar_descricao_automatico

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        String Pegar_Descricao="";
        
        estoque_Cadastrar_VIEW telaCadastrarProduto = new estoque_Cadastrar_VIEW();
        telaCadastrarProduto.setLocationRelativeTo(null);
        telaCadastrarProduto.setVisible(true);
        
        Pegar_Descricao = txt_Descricao.getText();
        objDTOAlterar.setDescricao(Pegar_Descricao);
                
        telaCadastrarProduto.exportar_ID_Produto(objDTOAlterar);
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
           Estoque_DAO objDAO = new Estoque_DAO();
           
           objDAO.ExcluirProduto(ID_Excluir_Dados);
           
           Consultar();
           SetarCampos();
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        estoque_Cadastrar_VIEW telaestoque_Cadastrar = new estoque_Cadastrar_VIEW();
        telaestoque_Cadastrar.setLocationRelativeTo(null);
        telaestoque_Cadastrar.setVisible(true);
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estoque_consulta_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estoque_consulta_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estoque_consulta_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estoque_consulta_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estoque_consulta_VIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JButton btn_Consulta;
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txt_Descricao;
    private javax.swing.JTextField txt_fltro;
    // End of variables declaration//GEN-END:variables


    public void Consultar(){
        int id;
       String nome, descricao;
       double preco;
       
       nome=txt_fltro.getText();
            
       Estoque_DAO EstDAO = new Estoque_DAO();
       
       DefaultTableModel model = (DefaultTableModel)Tabela.getModel();
       model.setNumRows(0);
       List<estoque_DTO> estDTO = EstDAO.Consultaproduto(nome);
                
        for (int num = 0; num<estDTO.size();num++) {
            model.addRow(new Object[]{
            estDTO.get(num).getId(),
            estDTO.get(num).getNome(),
            estDTO.get(num).getPreco()
            });
  
        }
        
        
    }
    
    private void SetarCampos(){
        txt_Descricao.setText("");
        txt_fltro.setText("");
    }



}
